version: '3.5'

services:
  v2ray:
    container_name: queen_v2ray
    image: v2fly/v2fly-core:v4.45.2
    restart: always
    expose:
      - '10086'
    volumes:
      - $HOME/queen/config.json:/etc/v2ray/config.json
      - /var/log/v2ray:/var/log/v2ray

  nginx:
    container_name: queen_nginx
    image: nginx:stable
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - $HOME/queen/nginx.conf:/etc/nginx/nginx.conf
      - $HOME/queen/web:/usr/share/nginx/html/demo
      - $HOME/queen/cert:/etc/nginx/cert